import type { PageTemplateMeta } from '@/types'
import { ComponentType } from '@/types'

export const double11Template: PageTemplateMeta = {
  id: 'double11',
  name: '双十一活动模板',
  description: '适合活动落地页，含主标题、主视觉、卖点和 CTA 按钮',
  cover: 'https://via.placeholder.com/480x270/1a0000/ffd166?text=Double11+Template',
  createPageData: () => ({
    id: 'template_double11',
    title: '双十一活动模板',
    style: {
      width: 1200,
      height: 1600,
      backgroundColor: '#120000',
    },
    components: [
      {
        id: 'double11_banner',
        type: ComponentType.TEXT,
        style: {
          top: 0,
          left: 0,
          width: 1200,
          height: 52,
          zIndex: 1,
          rotate: 0,
          fontSize: 18,
          color: '#ffffff',
          backgroundColor: '#d90429',
          fontWeight: 'bold',
          textAlign: 'center',
        },
        props: {
          content: '双11限时狂欢  官方补贴  今日开抢',
        },
      },
      {
        id: 'double11_title',
        type: ComponentType.TEXT,
        style: {
          top: 110,
          left: 150,
          width: 900,
          height: 100,
          zIndex: 1,
          rotate: 0,
          fontSize: 42,
          color: '#ffd166',
          backgroundColor: 'transparent',
          fontWeight: 'bold',
          textAlign: 'center',
        },
        props: {
          content: '年度底价 仅此一波',
        },
      },
      {
        id: 'double11_subtitle',
        type: ComponentType.TEXT,
        style: {
          top: 215,
          left: 200,
          width: 800,
          height: 56,
          zIndex: 1,
          rotate: 0,
          fontSize: 20,
          color: '#ffffff',
          backgroundColor: 'transparent',
          fontWeight: 'normal',
          textAlign: 'center',
        },
        props: {
          content: '11.11 00:00 - 23:59 全场限时抢购',
        },
      },
      {
        id: 'double11_hero',
        type: ComponentType.IMAGE,
        style: {
          top: 320,
          left: 150,
          width: 900,
          height: 620,
          zIndex: 1,
          rotate: 0,
          borderRadius: 16,
        },
        props: {
          src: 'https://via.placeholder.com/900x620/3a0a0a/ffd166?text=Double11+KV',
        },
      },
      {
        id: 'double11_point_1',
        type: ComponentType.TEXT,
        style: {
          top: 990,
          left: 150,
          width: 900,
          height: 56,
          zIndex: 1,
          rotate: 0,
          fontSize: 24,
          color: '#ffd166',
          backgroundColor: 'transparent',
          fontWeight: 'bold',
          textAlign: 'center',
        },
        props: {
          content: '跨店满减  |  爆款直降  |  限量优惠券',
        },
      },
      {
        id: 'double11_point_2',
        type: ComponentType.TEXT,
        style: {
          top: 1050,
          left: 250,
          width: 700,
          height: 48,
          zIndex: 1,
          rotate: 0,
          fontSize: 18,
          color: '#ffffff',
          backgroundColor: 'transparent',
          fontWeight: 'normal',
          textAlign: 'center',
        },
        props: {
          content: '精选爆款限时秒杀，优惠券可叠加使用',
        },
      },
      {
        id: 'double11_cta',
        type: ComponentType.BUTTON,
        style: {
          top: 1150,
          left: 400,
          width: 400,
          height: 64,
          zIndex: 1,
          rotate: 0,
          backgroundColor: '#ff3b30',
          color: '#ffffff',
          fontSize: 20,
          borderRadius: 32,
        },
        props: {
          content: '立即抢券',
          href: 'https://example.com',
          openInNewTab: true,
        },
      },
      {
        id: 'double11_notice',
        type: ComponentType.TEXT,
        style: {
          top: 1270,
          left: 250,
          width: 700,
          height: 68,
          zIndex: 1,
          rotate: 0,
          fontSize: 14,
          color: '#cccccc',
          backgroundColor: 'transparent',
          fontWeight: 'normal',
          textAlign: 'center',
        },
        props: {
          content: '优惠数量有限，具体活动规则以下单页说明为准',
        },
      },
    ],
  }),
}
